-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgmapjodPF68ChPojw
naoSMBgSlwdu8t8EXtdr0D92xYegCgYIKoZIzj0DAQehRANCAAQO7kR106f/rSuK
ea70hxozMGIOYnTdghlRwmibze0aeNsCeO2WAkoHVclJGbHLwBFq5wthnVXVbqKm
7to0IIMR
-----END PRIVATE KEY-----